import { cva } from "class-variance-authority";
import styles from "./flex.module.css";

export const flexVariants = cva(styles["lambda-flex"], {
	variants: {
		direction: {
			row: styles["lambda-flex-direction-row"],
			"row-reverse": styles["lambda-flex-direction-row-reverse"],
			column: styles["lambda-flex-direction-column"],
			"column-reverse": styles["lambda-flex-direction-column-reverse"],
			revert: styles["lambda-flex-direction-revert"],
			"revert-layer": styles["lambda-flex-direction-revert-layer"],
			initial: styles["lambda-flex-direction-initial"],
			inherit: styles["lambda-flex-direction-inherit"],
			unset: styles["lambda-flex-direction-unset"],
			"-moz-initial": styles["lambda-flex-direction-moz-initial"],
		},
		wrap: {
			nowrap: styles["lambda-flex-wrap-nowrap"],
			wrap: styles["lambda-flex-wrap-wrap"],
			"wrap-reverse": styles["lambda-flex-wrap-wrap-reverse"],
			inherit: styles["lambda-flex-wrap-inherit"],
			initial: styles["lambda-flex-wrap-initial"],
			revert: styles["lambda-flex-wrap-revert"],
			"revert-layer": styles["lambda-flex-wrap-revert-layer"],
			unset: styles["lambda-flex-wrap-unset"],
			"-moz-initial": styles["lambda-flex-wrap-moz-initial"],
		},
		align: {
			"flex-start": styles["lambda-flex-align-flex-start"],
			"flex-end": styles["lambda-flex-align-flex-end"],
			center: styles["lambda-flex-align-center"],
			end: styles["lambda-flex-align-end"],
			start: styles["lambda-flex-align-start"],
			"self-end": styles["lambda-flex-align-self-end"],
			"self-start": styles["lambda-flex-align-self-start"],
			baseline: styles["lambda-flex-align-baseline"],
			stretch: styles["lambda-flex-align-stretch"],
			normal: styles["lambda-flex-align-normal"],
			inherit: styles["lambda-flex-align-inherit"],
			initial: styles["lambda-flex-align-initial"],
			revert: styles["lambda-flex-align-revert"],
			"revert-layer": styles["lambda-flex-align-revert-layer"],
			unset: styles["lambda-flex-align-unset"],
			"-moz-initial": styles["lambda-flex-align-moz-initial"],
		},
		justify: {
			"-moz-initial": styles["lambda-flex-justify-moz-initial"],
			center: styles["lambda-flex-justify-center"],
			end: styles["lambda-flex-justify-end"],
			"flex-end": styles["lambda-flex-justify-flex-end"],
			"flex-start": styles["lambda-flex-justify-flex-start"],
			inherit: styles["lambda-flex-justify-inherit"],
			initial: styles["lambda-flex-justify-initial"],
			left: styles["lambda-flex-justify-left"],
			right: styles["lambda-flex-justify-right"],
			normal: styles["lambda-flex-justify-normal"],
			revert: styles["lambda-flex-justify-revert"],
			"revert-layer": styles["lambda-flex-justify-revert-layer"],
			"space-around": styles["lambda-flex-justify-space-around"],
			"space-between": styles["lambda-flex-justify-space-between"],
			"space-evenly": styles["lambda-flex-justify-space-evenly"],
			start: styles["lambda-flex-justify-start"],
			stretch: styles["lambda-flex-justify-stretch"],
			unset: styles["lambda-flex-justify-unset"],
		},
	},
	defaultVariants: {
		direction: "row",
		wrap: "nowrap",
		align: "flex-start",
		justify: "flex-start",
	},
});

/*
    "-moz-initial",
    "center",
    "end",
    "flex-end",
    "flex-start",
    "inherit",
    "initial",
    "left",
    "right",
    "normal",
    "revert",
    "revert-layer",
    "space-around",
    "space-between",
    "space-evenly",
    "start",
    "stretch",
    "unset", 
*/
